#!/bin/bash
if [ -f tabun_feed_release.db ]; then
 rm tabun_feed.db
 mv tabun_feed_release.db tabun_feed.db
else
 echo release db not found
 exit 1
fi

if [ -f config_release.cfg ]; then
 mv config.cfg config_beta.cfg
 mv config_release.cfg config.cfg
else
 echo config not found
 exit 2
fi
