#!/bin/bash
if [ -f tabun_feed_release.db ]; then
 echo beta already installed
 exit 1
else
 mv tabun_feed.db tabun_feed_release.db
fi

if [ -f config_beta.cfg ]; then
 mv config.cfg config_release.cfg
 mv config_beta.cfg config.cfg
else
 echo config not found
 exit 2
fi
